[flavor]
dark = "true"
name = "iterm2-dark"

[manager]
cwd = { fg = "#BFBAB0" }
hovered = { fg = "#0F1419", bg = "#F29718" }
preview_hovered = { fg = "#F29718" }
find_keyword = { fg = "#0F1419", bg = "#F29718" }
marker_selected = { fg = "#C2D94C", bg = "#16242E" }
marker_copied   = { fg = "#59C2FF", bg = "#16242E" }
marker_cut      = { fg = "#FF7733", bg = "#16242E" }

[status]
normal = { fg = "#BFBAB0", bg = "#0F1419" }
insert = { fg = "#0F1419", bg = "#59C2FF" }
select = { fg = "#0F1419", bg = "#F29718" }

[completion]
active   = { fg = "#0F1419", bg = "#F29718" }
inactive = { fg = "#BFBAB0", bg = "#131E27" }

[input]
title = { fg = "#59C2FF" }
border = { fg = "#20272C" }
selected = { fg = "#0F1419", bg = "#F29718" }

[progress]
normal = { fg = "#C2D94C", bg = "#0A0E12" }
error  = { fg = "#FF3333", bg = "#0A0E12" }

[which]
mask  = { bg = "#0F1419" }
cand  = { fg = "#59C2FF" }
rest  = { fg = "#BFBAB0" }
desc  = { fg = "#95E6CB" }
separator = "#5C6773"

[help]
on  = { fg = "#F29718" }
off = { fg = "#5C6773" }

[log]
error = { fg = "#FF3333" }
warn  = { fg = "#FF7733" }
info  = { fg = "#59C2FF" }
debug = { fg = "#5C6773" }

